subinclude("//e2e/build_defs:please_repo")

please_repo_e2e_test(
    name = "replace_test",
    get_wildcards = ["github.com/aws/amazon-ssm-agent/..."],
    plz_command = "plz test",
    repo = "test_repo",
)
