go_library(
    name = "licences",
    srcs = ["licences.go"],
    deps = ["//resolve", "//resolve/model", "//resolve/driver",        "//third_party/go/github.com/google/go-licenses",
 "//third_party/go/golang.org/x/tools",
],
    visibility = ["//:go-deps"],
)